/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container": "#eceef0",
        "primary-fixed-dim": "#70dc8f",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "primary-fixed": "#8cf9a9",
        "outline": "#6e7a6e",
        "secondary": "#575e70",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "on-background": "#191c1e",
        "tertiary-container": "#007bba",
        "tertiary": "#006194",
        "background": "#f7f9fb",
        "on-tertiary-fixed": "#001d31",
        "surface-tint": "#006d36",
        "secondary-fixed-dim": "#c0c6db",
        "surface-dim": "#d8dadc",
        "primary-container": "#008744", // Verde URP Oficial
        "on-surface": "#191c1e",
        "surface-card": "#ffffff",
        "tertiary-fixed-dim": "#93ccff",
        "surface-container-highest": "#e0e3e5",
        "on-surface-variant": "#3e4a3f",
        "inverse-primary": "#70dc8f",
        "on-primary-fixed-variant": "#005227",
        "inverse-on-surface": "#eff1f3",
        "surface-bright": "#f7f9fb",
        "inverse-surface": "#2d3133",
        "surface": "#f7f9fb",
        "surface-variant": "#e0e3e5",
        "on-secondary-fixed": "#141b2b",
        "surface-container-high": "#e6e8ea",
        "on-error-container": "#93000a",
        "on-primary-container": "#f9fff6",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#cce5ff",
        "border-subtle": "#e2e8f0",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#00210c",
        "on-secondary-fixed-variant": "#404758",
        "outline-variant": "#bdcabc",
        "secondary-container": "#d9dff5",
        "secondary-fixed": "#dce2f7",
        "medical-accent": "#0ea5e9",
        "on-tertiary-container": "#fefdff",
        "on-secondary-container": "#5c6274",
        "primary": "#006b35",
        "on-tertiary-fixed-variant": "#004b73",
        "text-slate": "#1e293b",
        // URP Tailwind helpers & Anti-AI design tokens
        urp: {
          50: '#f0fdf4',
          100: '#dcfce7',
          300: '#8cf9a9',
          400: '#00a859',
          500: '#22c55e',
          700: '#008744',
          800: '#006b35',
          900: '#004d26',
          charcoal: '#12161a',
          surface: '#1e242c',
          gold: '#f59e0b',
        }
      },
      boxShadow: {
        'brutal': '4px 4px 0px #0f172a',
        'brutal-sm': '2px 2px 0px #0f172a',
        'brutal-lg': '6px 6px 0px #0f172a',
        'brutal-green': '4px 4px 0px #00572b',
        'brutal-gold': '4px 4px 0px #d97706',
        'tactile': '0 2px 0 #0f172a',
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        '2xl': "1rem",
        '3xl': "1.5rem",
        'urp-card': "36px",
        full: "9999px"
      },
      spacing: {
        "container-max": "1280px",
        xs: "8px",
        sm: "16px",
        xl: "64px",
        "margin-mobile": "16px",
        lg: "40px",
        gutter: "24px",
        base: "4px",
        md: "24px"
      },
      fontFamily: {
        "title-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        caption: ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        sans: ["Inter", "system-ui", "sans-serif"],
        display: ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        caption: ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
